# Generated by Django 2.0.5 on 2018-07-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0023_leaseproperty_totalcontractprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='', max_length=255)),
                ('details', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='leaseProperty',
        ),
        migrations.DeleteModel(
            name='salesProperty',
        ),
    ]
